### ISSUE TITLE
Handle ratelimiting errors nicely

### ISSUE THREAD

**Issue by glasnt** [glasnt/octohat#10]
At the moment, if you hit the rate limit (60/hour untokened, 5000/hour tokened), the app will say the repo doesn't exist, instead of saying you've hit the limit. It should ideally also get the X-RateLimit-Reset header and return the time to try again, possibly with a `(in xx minutes)` message.

**Comment by stewart-ibm** [comment]
Yeah, I was hitting this too pretty heavily on the repos I was trying.

**Comment by glasnt** [comment]
Between the foundation in #15 and my small alterations in #20, this is totally a thing \o/
