### ISSUE TITLE
Include name as well as username in output

### ISSUE THREAD

**Issue by stewart-ibm** [glasnt/octohat#12]
This would help identify the people when many contributors don't have gravitars, as well as making the text output more usable in release notes.

**Comment by tclark** [comment]
I implemented this here https://github.com/tclark/octohat/tree/add-name-to-output and find it useful since my students have a knack for choosing indecipherable user names.

**Comment by glasnt** [comment]
@tclark could you please bundle up these changes you've made in your fork and throw them in a pull request for me? :)

**Comment by glasnt** [comment]
Resolved in #29
