### ISSUE TITLE
Travis-CI GITHUB_TOKEN environment variable not found

### ISSUE THREAD

**Issue by glasnt** [glasnt/octohat#30]
The `DEBUG` function shows that the `GITHUB_TOKEN` isn't being seen by the script. I've setup this up as an secret environment variable as not to expose it to the public, but it should still be visible to the script. 

The problem is that to get all the contributor information for octohat now takes more than 60 API calls, which means that without the token the self-referencing test cannot run. :disappointed:

**Comment by tclark** [comment]
I looked at this while setting up travis integration on my own repo.  My understanding is that secret environment variables are not accessible to test that are run when a nonprivileged user submits a pull request.

**Comment by glasnt** [comment]
Ah.. um.. right. That would explain why my PRs were never experiencing issues. Goodness. I found the [reference](http://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables) to what you're talking about: 

> ... we do not provide these values to untrusted builds, triggered by pull requests from another repository.

Then this is literally a case of "it works for me". Awkward. 

This limitation also applies to encrypted values. 

I've been using `GITHUB_TOKEN`'s generated from my own user, but with only `public_repo` permissions. I really didn't want to ever make this public. 

_~ ~ ... research... ~ ~_

Turns out I'm right, because what I *thought* was the basic R/O scope isn't - the `public_repo` scope allows read/write access. What I need is a token with no scopes, which is just a public read. 

If a no scope token is read only, then I think it will be ok to add this into `.travis.yml` in cleartext and commit it to the repo. At any point I can revoke the token in just a few clicks in the github UI, if required.  

This solution still makes me feel a bit ikky :/

**Comment by glasnt** [comment]
GitHub support have been incredibly helpful, and I've copied their response below, for posterity, highlighting mine. 

> Your intuition is spot on. Publishing scoped tokens in a public place isn't something we recommend (we recommend that you treat them as passwords), and if you try to do that on GitHub (i.e. push it to a public repository) -- the token will be **automatically revoked**:

> https://github.com/blog/1956-keeping-github-oauth-tokens-safe

> Currently, scopeless tokens aren't revoked automatically on GitHub, so you should be able to push them to a public repository. The risk of doing that is, as you mentioned, that anyone can drain the hourly API quota for the GitHub account which owns the token (API quotas are per-user, not per-user per-token). That's not a security issue for your account (since no data other than publicly available data can be read), but it might cause application-level problems for you. If someone drains your API quota -- then all other applications you authorized with your GitHub account will "starve" and probably not do the things you expect them to.

> In addition to that, if someone takes the token and starts making lots of requests which completely ignore the regular and the abuse rate limits -- that would be considered abuse of the API:

> https://developer.github.com/guides/best-practices-for-integrators/#dealing-with-rate-limits

> In some situations, that might get the account which is making those requests temporarily suspended (until the problem is resolved).

> For your specific situation, my wish would be for the service you're using (Travis) to support this interaction in a better way so that you don't need to publish any tokens. If you don't want to wait for that -- **you have the option of publicly publishing your scopeless token.**
