### ISSUE TITLE
Create a list of known github robots to exclude

### ISSUE THREAD

**Issue by glasnt** [glasnt/octohat#39]
There are some robots that automatically create issues and pull requests that probably shouldn't be attributed as contributions. 

From what I can tell, these include: 
 * gitter-badger
 * a travis-ci bot of sorts
 * probably a circle-ci bot as well

Ideally, there should be a file of a list of robots that are removed from the two contributors before they are compared

**Comment by Ketsuban** [comment]
There's also [bors](https://github.com/bors) and [bors-servo](https://github.com/bors-servo) which help out with projects under the Rust and Servo umbrellas respectively, though Rust at least has [erred in favour of crediting the bot as if it's a human contributor](http://blog.rust-lang.org/2015/09/17/Rust-1.3.html) which may factor into your decision.

**Comment by glasnt** [comment]
@Ketsuban thanks for that link.  It looks like that's a raw list of github displaynames (or usernames where not available), sorted with caps first. I'm not actually seeing any direct reference on that page to adding/not-adding robots (unless that's been mentioned in prior release notes?)

**Comment by Ketsuban** [comment]
My point was merely that bors is listed as a contributor despite being a bot which handles merges and running tests and things. Sorry, looks like I wasn't clear enough why I was linking that. :smile:

**Comment by timgws** [comment]
Surely if we are going to credit humans, why would you also not want to have bots included in the contributors list?

**Comment by Ketsuban** [comment]
The purpose of this repository is to be a list of known Github bots. What people do with that information is up to them. :)

**Comment by Ketsuban** [comment]
It defeats the purpose of the repo if things are credited to the bot when all it did was the mechanical process of running tests and handling the actual commit.

**Comment by glasnt** [comment]
I think I'll keep the robots in for now. The robots were built by humans, so it's kinda fitting that they're helping :)
